version: "3.9"

services:
  database:
    # ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: db_deliveries_quotations
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=deliveries_quotations
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: deliveries_quotations
    restart: always
    ports:
      - 3000:3000
      - 9229:9229 # Você pode inserir essa porta tbm pra poder usar o debug
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
